### PR TITLE
Fixed a little spelling & grammar.

### PR DESCRIPTION
**Pull request by parndt**
💜💛❤️💙💚

### CODE REVIEW

**Comment by rachelmyers** [comment]
Thanks for this! :heart:

**Comment by tjgrathwell** [comment]
nitpick: I feel like `underrepresented` is more correct without the hyphen: https://www.google.com/trends/explore#q=under-represented%2C%20underrepresented&cmpt=q&tz=Etc%2FGMT%2B7

**Comment by siruguri** [comment]
[Chicago Style Guide](
http://www.chicagomanualofstyle.org/16/images/ch07_tab01.pdf) would agree -
see page 10.


On Fri, Jun 19, 2015 at 12:22 PM, Travis Grathwell <notifications@github.com

**Comment by rachelmyers** [comment]
Sorry for merging this without waiting for comments! Since it's merged, maybe the hyphen fix could be a separate PR?

**Comment by parndt** [comment]
Thanks for pointing that out 😁

**Pull request merged**
